### ISSUE TITLE
Unable to fetch Files and Directories

### ISSUE THREAD

**Issue by tutorialdrive** [homerours/cosmic#3]
There is everything what I want in this app. Good UI is +. 
But issues are,
Last added, Last played are return nothing, blank page.
- Select directory not working, display blank page (No directory list)
- I am using android version 4.4.4

**Comment by homerours** [comment]
Hello,
Did you installed the Cordova file plugin (and the other required plugins) ? If yes, can you show me the JavaScript console logs?

You have to select the directories where you store your music files (mp3, m4a) before having them in the last added, last played playlists. To do so: settings -> Manage music directories -> (+) (up right) -> select the directory you want to scan and HOLD on his name

Hope it helped ;)

**Comment by tutorialdrive** [comment]
## Here is a final output when app run. No other o/p

Total time: 14.682 secs
Built the following apk(s):
    /home/tutorial/Projects/m-music/platforms/android/build/outputs/apk/android-debug.apk
Installing app on emulator...
Using apk: /home/tutorial/Projects/m-music/platforms/android/build/outputs/apk/android-debug.apk
INSTALL SUCCESS
Unlocking screen...
Launching application...

## LAUNCH SUCCESS

I am using Ubuntu 14.04 LTS with Cordova CLI

**Comment by homerours** [comment]
Thank you. But that's the Cordova/Ionic logs when your app is built. I was speaking about the Javascript logs that you can see using the chrome developper tools: http://developer.telerik.com/featured/a-concise-guide-to-remote-debugging-on-ios-android-and-windows-phone/

**Comment by homerours** [comment]
I'm using Cordova CLI 5.3.1, Gulp 3.9.0 (for scss, templateCache, ...), ionic lib 1.0.1 (not 1.1.0), ionic CLI 1.6.4.
I've build a debug android app: https://www.dropbox.com/sh/tudn23c26jc6fya/AABh8mHXAbDAzxMsaTtXjeVDa?dl=0

Is it working for you?

**Comment by tutorialdrive** [comment]
Yes. Its working fine now.
Let me try on with my windows machine with above configurations
Thanks :+1:
