### ISSUE TITLE
Application Turn off on back button

### ISSUE THREAD

**Issue by tutorialdrive** [homerours/cosmic#4]
Working great in android if I press minimize button (button to minimize app). But If I press back button and exit application, it turn off. Is there any way/ logic to resolve this ?
Please share logic if available so I can also contribute in it.

**Comment by homerours** [comment]
Thank you for reporting this issue. I fixed it with [a "back as home" button plugin](https://github.com/amitsinha559/cordova-plugin-back-as-home), see the commit. Is is working for you?
