### ISSUE TITLE
Play / Pause issue with earphones with mic

### ISSUE THREAD

**Issue by tutorialdrive** [homerours/cosmic#5]
I Play music with earphone with play/pause button with mic. Its Play and pause music on default app in android. But while using Cosmic, if I press mic button from earphone, its start default music app as well and play music from both apps.

**Comment by homerours** [comment]
Thank you for reporting this.
I'm aware of this issue. I also would like to pause audio when unplugging the earphones.
This can be solve with an android plugin. I am going to update my [cordova music controls plugin](https://github.com/homerours/cordova-music-controls-plugin).
